all:
  title:        Our fridge system
  help:         http://code.google.com/p/fridgex
  
  surcharge:      10%
  surcharge_units:    100   # calculate surcharge to 100ths of a $
  
  credit_max:     50       # max credit per purchase in $; will throw an error if more
  
  mail:
    charset:    utf-8
    hostname:   localhost
    username:
    password:
    
    from:       Fridex
    address:    fridex@jevon.org

  # stock loss users. only the first username will be used when administrators
  # create a stock loss "purchase"
  losses:
    users:
      - admin

  # for home page statistics purposes, ignore all of these users
  ignore:
    users:
      - admin

  permission:
    list:
      - activity
      - edit
      - inventory
      - delete
      - verify
      - cancel
      - stock
      - user
      - credit
      - permission
    
    edit:       add and edit products, view surcharge
    cancel:     cancel purchases
    stock:      register stock losses
    delete:     delete products and users
    inventory:  set product inventory
    user:       add, edit and list users
    credit:     set user credit
    activity:   view recent activity
    verify:     verify product credits
    permission: set user permissions    