all:
  # title:        Our Fridge System
  # help:         http://code.google.com/p/fridgex
  
  mail:
    charset:    utf-8
    hostname:   localhost
    username:
    password:
    
    from:       Fridex
    address:    fridex@jevon.org

  permission:
    list:
      - edit
      - user
      - delete
      - verify
      - credit
      - inventory