default:
  http_metas:
    content-type: text/html

  metas:
    title:        Fridge
    robots:       index, follow
    description:  A fridge billing system for a community of likely computer scientists
    keywords:     fridge, billing, community, symfony
    language:     en

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
