<?php
// auto-generated by sfPropelCrud
// date: 2008/07/24 15:06:18
?>
<?php use_helper('Object') ?>

<?php if ($sf_request->hasErrors()): ?>
<div class="error">
  <?php echo implode("; ", $sf_request->getErrors()); ?> - please try again
</div>
<?php endif; ?>

<?php echo form_tag('product_admin/update', 'multipart=true') ?><?php /* multipart required for file upload */ ?>

<?php echo object_input_hidden_tag($product, 'getId') ?>

<table>
<tbody>
<tr>
  <th>Title:</th>
  <td><?php echo object_input_tag($product, 'getTitle', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Price:</th>
  <td>$ <?php echo object_input_tag($product, 'getPrice', array (
  'size' => 7,
)) ?></td>
</tr>
<?php if ($user->canSetInventory($product)) { ?>
<tr>
  <th>Inventory:</th>
  <td><?php echo object_input_tag($product, 'getInventory', array (
  'size' => 7,
)) ?></td>
</tr>
<?php } ?>
<tr>
  <th>Image:</th>
  <td><?php echo $product->getImageUrl() ? image_tag($product->getImageUrl()) : "(empty)"; ?><br>

    Upload new: <?php echo input_file_tag('upload_image') ?> (optimal 100x140)<br>

</td>
</tr>
<tr>
  <th>Sort order:</th>
  <td><?php echo object_input_tag($product, 'getSortOrder', array (
  'size' => 7,
)) ?></td>
</tr>
<tr>
  <th>Hidden:</th>
  <td><?php echo object_checkbox_tag($product, 'getIsHidden', array (
)) ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($product->getId()): ?>
  <?php if ($user->canDeleteProduct($product)) { ?>
  	&nbsp;<?php echo link_to('delete', 'product_admin/delete?id='.$product->getId(), 'post=true&confirm=Are you sure?') ?>
  <?php } ?>
  &nbsp;<?php echo link_to('cancel', 'product/show?id='.$product->getId()) ?>
<?php else: ?>
  &nbsp;<?php echo link_to('cancel', 'product/list') ?>
<?php endif; ?>
</form>
