<?php
// auto-generated by sfPropelCrud
// date: 2008/07/23 15:51:32
?>
<div id="product_show">

<h1><?php echo $product->getTitle(); ?></h1>

&nbsp;<?php echo link_to('< Back to product list', 'product/list') ?>

<div class="info">
	<table>
	<tbody>
	<tr>
	<th>Price: </th>
	<td><?php echo my_format_currency(apply_surcharge($product->getPrice())) ?>
	<?php if ($user && $user->canViewSurcharge() && get_surcharge_for($product->getPrice())) { ?>, includes a surcharge of <?php echo my_format_currency(get_surcharge_for($product->getPrice())); ?><?php } ?></td>
	</tr>
	<tr>
	<th>Inventory: </th>
	<td><?php echo format_number($product->getInventory()) ?></td>
	</tr>
	<tr>
	<th>Image: </th>
	<td><?php echo image_tag($product->getImageUrl()) ?></td>
	</tr>
	</tbody>
	</table>
</div>

<div class="purchase">

<?php if ($user) { ?>

<?php if ($product->getInventory() > 0) { ?>

<?php echo form_tag("product/purchase"); ?>
<?php echo input_hidden_tag("id", $product->getId()); ?>
	<table>
	<thead>
	<tr>
		<th colspan="2">Purchase</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<th>Quantity: </th>
		<td><?php echo input_tag("quantity", 1); ?></td>
	</tr>
	<tr>
		<td></td>
		<td>
			<?php echo submit_tag("Purchase"); ?>
			<?php if ($user->canChargeStockLosses()) { ?>
				<?php echo submit_tag("Purchase as a stock loss", array("name" => "stock_loss")); ?>
			<?php } ?>
		</td>
	</tr>
	</tbody>
	</table>
</form>

<?php } else { ?>

<div class="disabled">None available for purchase</span>

<?php } ?>

<?php if ($user->canCredit($product)) { ?>

<?php echo form_tag("product/credit"); ?>
<?php echo input_hidden_tag("id", $product->getId()); ?>
	<table>
	<thead>
	<tr>
		<th colspan="2">Credit</th>
	</tr>
	</thead>
	<tbody>
	<tr>
		<th>Quantity: </th>
		<td><?php echo input_tag("quantity", 1); ?></td>
	</tr>
	<tr>
		<th>Price paid each: </th>
		<td>$ <?php echo input_tag("price", 1, array("size" => 10)); ?></td>
	</tr>
	<tr>
		<td></td>
		<td><?php echo submit_tag("Credit"); ?></td>
	</tr>
	</tbody>
	</table>
</form>

<?php } ?>

<?php } else { ?>

<?php if ($user) { ?>
<div class="disabled">You cannot afford to purchase this.</div>
<?php } else { ?>
<div class="disabled">You need to be <?php echo link_to("logged in", "security/index"); ?> to buy this.</div>
<?php } ?>

<?php } ?>

<?php if ($user && $user->canEditProduct($product)) { ?>
<?php echo link_to("Edit product", "product_admin/edit?id=".$product->getId()); ?>
<?php } ?>

</div>