<?php
// auto-generated by sfPropelCrud
// date: 2008/07/24 15:35:45
?>
<?php

/**
 * user_admin actions.
 *
 * @package    fridge
 * @subpackage user_admin
 * @author     Your name here
 * @version    SVN: $Id: actions.class.php 3335 2007-01-23 16:19:56Z fabien $
 */
class user_adminActions extends myActions
{
	/**
	 * Only users are allowed to access pages in here.
	 * that have the appropriate permissions
	 */
	public function preExecute() {
		parent::preExecute();

		// get the user object
		$this->current_user = $this->getUserObject();

		if (!($this->current_user->canListUsers()))
			$this->insufficientRights();
	}

  public function executeIndex()
  {
    return $this->forward('user_admin', 'list');
  }

  public function executeList()
  {
    $this->users = UserPeer::doSelect(new Criteria());
  }

  public function executeShow()
  {
    $this->user = UserPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->user);
  }

  public function executeCreate()
  {
    $this->user = new User();

    $this->setTemplate('edit');

	if (!($this->current_user->canEditUser($this->user)))
		$this->insufficientRights();

  }

  public function executeEdit()
  {
    $this->user = UserPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->user);

	if (!($this->current_user->canEditUser($this->user)))
		$this->insufficientRights();

  }

	public function validateUpdate() {
		$c = new Criteria();
		$c->add(UserPeer::EMAIL, $this->getRequestParameter("email"));
		$user = UserPeer::doSelectOne($c);
		if ($user && $user->getId() != $this->getRequestParameter("id")) {
			$this->getRequest()->setError("email", "email address already exists in the system");
		}

		return !$this->getRequest()->hasErrors();
	}

	public function handleErrorUpdate() {
		// error in form => redirect to login page
		if ($this->getRequestParameter("id")) {
			return $this->forward("user_admin", "edit", array("id" => $this->getRequestParameter("id")));
		} else {
			return $this->forward("user_admin", "create");
		}
	}

  public function executeUpdate()
  {
    if (!$this->getRequestParameter('id'))
    {
      $user = new User();
    }
    else
    {
      $user = UserPeer::retrieveByPk($this->getRequestParameter('id'));
      $this->forward404Unless($user);
    }

	if (!($this->current_user->canEditUser($this->user)))
		$this->insufficientRights();

    $user->setId($this->getRequestParameter('id'));
    $user->setEmail($this->getRequestParameter('email'));
    $user->setName($this->getRequestParameter('name'));
    $user->setNickname($this->getRequestParameter('nickname'));

	if ($this->current_user->canSetCredit($this->user))
    	$user->setAccountCredit($this->getRequestParameter('account_credit'));

    $user->save();

    // if adding a new user, send an email
    if (!$this->getRequestParameter('id')) {
		$this->getRequest()->setParameter("user", $user->getId());

		$raw_email = $this->sendEmail('mail', 'signup');
		$this->logMessage($raw_email, "debug");
	}

    return $this->redirect('user_admin/show?id='.$user->getId());
  }

  public function executeDelete()
  {
    $user = UserPeer::retrieveByPk($this->getRequestParameter('id'));

    $this->forward404Unless($user);

	if (!($this->current_user->canDeleteUser($this->user)))
		$this->insufficientRights();

    $user->delete();

    return $this->redirect('user_admin/list');
  }
}
