<?php
// auto-generated by sfPropelCrud
// date: 2008/07/25 14:15:28
?>
<h1>Unverified purchases</h1>

<?php use_helper("My"); ?>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Date</th>
  <th>User</th>
  <th>Product</th>
  <th>Quantity</th>
  <th>Price</th>
  <th>Notes</th>
</tr>
</thead>
<tbody>
<?php $shown = false; ?>
<?php foreach ($purchases as $purchase): ?>
<?php if ($user->canVerifyActualCredit($purchase)) { ?>
	<?php $shown = true; ?>
<tr>
    <td class="number"><?php echo $purchase->getId() ?></td>
      <td><?php echo my_format_date($purchase->getCreatedAt()) ?></td>
      <td><?php echo $purchase->getUser() ? link_to($purchase->getUser()->getNickname(), "user_admin/show?id=".$purchase->getUser()->getId(), array("class" => "username")) : "null" ?></td>
      <td>
      <?php if ($purchase->getIsDirectCredit()) { ?>
			<?php if ($purchase->getPrice() > 0) { ?>
				Direct credit by <span class="username"><?php echo $purchase->getCreditedByUser() ? link_to($purchase->getCreditedByUser()->getNickname(), "user_admin/show?id=". $purchase->getCreditedByUser()->getId()) : "null"; ?></span>
			<?php } else { ?>
				Direct debit by <span class="username"><?php echo $purchase->getCreditedByUser() ? link_to($purchase->getCreditedByUser()->getNickname(), "user_admin/show?id=". $purchase->getCreditedByUser()->getId()) : "null"; ?></span>
			<?php } ?>
    	<?php } else { ?>
      		<?php echo $purchase->getProduct() ? link_to($purchase->getProduct()->getTitle(), "product/show?id=".$purchase->getProduct()->getId()) : "null" ?>
      	<?php } ?>
      </td>
      <td class="number"><?php echo format_number($purchase->getQuantity()) ?></td>
      <td class="currency"><?php echo my_format_currency($purchase->getPrice()) ?></td>
      <td>
      <?php echo form_tag("purchase/update"); ?>
      <?php echo input_hidden_tag("id", $purchase->getId()); ?>
      <?php echo input_hidden_tag("verify", true); ?>
      Notes:
      <?php echo input_tag("notes", "", array("size" => 20)); ?>
      <?php echo submit_tag("verify credit"); ?>
      </form>
      </td>
  </tr>
<?php } ?>
<?php endforeach; ?>
<?php if (!$purchases || !$shown) { ?>
<tr>
	<td colspan="7" class="no_activity">No unverified purchases to show!</td>
</tr>
<?php } ?>
</tbody>
</table>
