<?php
// auto-generated by sfPropelCrud
// date: 2008/07/25 14:15:28
?>
<h1>unverified purchases</h1>

<?php use_helper("Number"); ?>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>User</th>
  <th>Product</th>
  <th>Quantity</th>
  <th>Price</th>
  <th>Created at</th>
  <th>Notes</th>
</tr>
</thead>
<tbody>
<?php foreach ($purchases as $purchase): ?>
<tr>
    <td><?php echo $purchase->getId() ?></td>
      <td><?php echo $purchase->getUser() ? link_to($purchase->getUser()->getEmail(), "user/show?id=".$purchase->getUser()->getId()) : "null" ?></td>
      <td><?php echo $purchase->getProduct() ? link_to($purchase->getProduct()->getTitle(), "product/show?id=".$purchase->getProduct()->getId()) : "null" ?></td>
      <td><?php echo format_number($purchase->getQuantity()) ?></td>
      <td><?php echo format_currency($purchase->getPrice()) ?></td>
      <td><?php echo $purchase->getCreatedAt() ?></td>
      <td>
		  <?php echo form_tag("purchase/update"); ?>
		  <?php echo input_hidden_tag("id", $purchase->getId()); ?>
		  <?php echo input_hidden_tag("verify", true); ?>
		  Notes:
		  <?php echo input_tag("notes", "", array("size" => 20)); ?>
		  <?php echo submit_tag("verify credit"); ?>
		  </form>
      </td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>
