<?php
// auto-generated by sfPropelCrud
// date: 2008/07/25 14:15:28
?>
<h1>Recent activity</h1>

<?php use_helper("My"); ?>

<table>
<thead>
<tr>
  <th>Id</th>
  <th>Date</th>
  <th>User</th>
  <th>Product</th>
  <th>Quantity</th>
  <th>Credit</th>
  <th>Debit</th>
  <th>Notes</th>
</tr>
</thead>
<tbody>
<?php foreach ($purchases as $purchase): ?>
<tr>
    <td class="number"><?php echo $purchase->getId() ?></td>
      <td><?php echo my_format_date($purchase->getCreatedAt()) ?></td>
      <td><?php echo $purchase->getUser() ? link_to($purchase->getUser()->getNickname(), "user_admin/show?id=".$purchase->getUser()->getId()) : "null" ?></td>
      <td><?php echo $purchase->getProduct() ? link_to($purchase->getProduct()->getTitle(), "product/show?id=".$purchase->getProduct()->getId()) : "null" ?></td>
      <td class="number"><?php echo format_number($purchase->getQuantity()) ?></td>
<?php if ($purchase->getQuantity() < 0) { ?>
      <td class="currency"></td>
      <td class="currency"><?php echo my_format_currency(-$purchase->getPrice()) ?></td>
<?php } else { ?>
      <td class="currency"><?php echo my_format_currency($purchase->getPrice()) ?></td>
      <td class="currency"></td>
<?php } ?>
      <td><?php echo $purchase->getNotes(); ?>
		<?php if ($purchase->getQuantity() > 0 && !$purchase->isVerified()) { ?>
			<?php echo link_to("unverified", "purchase/credit"); ?>
		<?php } ?>
	  </td>
  </tr>
<?php endforeach; ?>
<?php if (!$purchases) { ?>
<tr>
	<td colspan="8" class="no_activity">No recent activity to show!</td>
</tr>
<?php } ?>
</tbody>
</table>
