propel:
  user:
    id:
    email:          varchar(255)
    name:           varchar(255)
    nickname:       varchar(255)
    password_hash:  varchar(255)
    
    created_at:
    updated_at:
    last_login:     timestamp
    
    # account credit
    account_credit:
      type: decimal
      size: 9
      scale: 2

    # autologin
    login_key:      varchar(16)     # 16-character random hex
  
  # user permissions
  user_permission:
    id:
    user_id:        { type: integer, foreignTable: user, foreignReference: id, onDelete: cascade }
    permission:     varchar(32)       # some sort of user permission key (tbd)
    created_at:

  # products in the fridge
  product:
    id:
    title:          varchar(255)
    price:          # per item
      type: decimal
      size: 9
      scale: 2
    inventory:      integer
    image_url:      varchar(255)
    sort_order:     integer
    created_at:
    updated_at:

  # people make purchases or credits (they are stored in the same table)
  purchase:
    id:
    user_id:        { type: integer, foreignTable: user, foreignReference: id, onDelete: setnull }
    product_id:     { type: integer, foreignTable: product, foreignReference: id, onDelete: setnull }
    quantity:       integer
    price:          # per item (incl surcharge)
      type: decimal
      size: 9
      scale: 2
    created_at:
    
    # when crediting, they need to be verified by someone with authority
    verified_by_id: { type: integer, foreignTable: user, foreignReference: id, onDelete: setnull }
    verified_at:    timestamp
    notes:          varchar(255)
    
    # when a surcharge applies, the amount added on is stored in here
    # (per item)
    surcharge:
      type: decimal
      size: 9
      scale: 2
      
    cancelled_at:   timestamp
    cancelled_by_id:   { type: integer, foreignTable: user, foreignReference: id, onDelete: setnull }
    
    # direct credit is also seen as a purchase
    is_direct_credit:   boolean
    credited_by:        { type: integer, foreignTable: user, foreignReference: id, onDelete: setnull }
    
  # emails
  email:
    id:
    user_id:      { type: integer, foreignTable: user, foreignReference: id, onDelete: setnull }
    to_address:   varchar(255)
    to_name:      varchar(255)
    from_address: varchar(255)
    from_name:    varchar(255)
    subject:      varchar(255)
    body:         clob
    created_at:
    updated_at:
    sent_at:      timestamp
    
  email_attachment:
    id:
    email_id:     { type: integer, foreignTable: email, foreignReference: id, onDelete: cascade }
    filename:     varchar(255)
    media_type:   varchar(255)
    content:      blob
    created_at:

  