<?php
// auto-generated by sfPropelCrud
// date: 2008/07/24 15:35:45
?>
<?php use_helper('Object') ?>

<h1>edit profile</h1>

<?php if ($sf_request->hasErrors()): ?>
<div class="error">
  <?php echo implode("; ", $sf_request->getErrors()); ?> - please try again
</div>
<?php endif; ?>

<?php echo form_tag('user/update') ?>

<table>
<tbody>
<tr>
  <th>Email:</th>
  <td>Currently <?php echo $user->getEmail(); ?><br>
  	<?php echo object_input_tag($user, 'getEmail', array (
  'size' => 40,
)) ?></td>
</tr>
<tr>
  <th>Email (confirm):</th>
  <td><?php echo input_tag("email_confirm", "", array("size" => 80)); ?></td>
</tr>
<tr>
  <th>Name:</th>
  <td><?php echo object_input_tag($user, 'getName', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Nickname:</th>
  <td><?php echo object_input_tag($user, 'getNickname', array (
  'size' => 80,
)) ?></td>
</tr>
<tr>
  <th>Password:</th>
  <td><?php echo input_password_tag("password", "", array("size" => 40)); ?></td>
</tr>
<tr>
  <th>Password (confirm):</th>
  <td><?php echo input_password_tag("password_confirm", "", array("size" => 40)); ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo submit_tag('save') ?>
<?php if ($user->getId()): ?>
  &nbsp;<?php echo link_to('cancel', 'user_admin/show?id='.$user->getId()) ?>
<?php endif; ?>
</form>
