<?php
// auto-generated by sfPropelCrud
// date: 2008/07/24 15:35:45
?>
<h1>Manage Users</h1>

<?php use_helper("My"); ?>

<table>
<thead>
<tr>
  <th>Email</th>
  <th>Name</th>
  <th>Nickname</th>
  <th>Last login</th>
  <th>Account credit</th>
  <th>Recent activity</th>
</tr>
</thead>
<tbody>
<?php foreach ($users as $user): ?>
<tr>
      <td><?php echo link_to($user->getEmail(), 'user_admin/show?id='.$user->getId()) ?></td>
      <td><?php echo $user->getName() ?></td>
      <td><?php echo $user->getNickname() ?></td>
      <td><?php echo my_format_date($user->getLastLogin()) ?></td>
      <td class="number"><?php echo my_format_currency($user->getAccountCredit()) ?></td>
      <td><?php echo $user->getRecentActivity() ?></td>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('Create new user', 'user_admin/create') ?>
