<?php
// auto-generated by sfPropelCrud
// date: 2008/07/24 15:35:45
?>
<div id="user_admin_permissions">
<h1>User Permissions</h1>

<?php use_helper("My"); ?>

<table>
<thead>
<tr>
  <th>Email</th>
  <th>Name</th>
  <th>Nickname</th>
<?php foreach (sfConfig::get("app_permission_list", array()) as $permission) { ?>
  <th class="permission"><?php echo $permission; ?></th>
<?php } ?>
</tr>
</thead>
<tbody>
<?php foreach ($users as $user): ?>
<tr>
      <td><?php echo link_to($user->getEmail(), 'user_admin/show?id='.$user->getId()) ?></td>
      <td><?php echo $user->getName() ?></td>
      <td><span class="username"><?php echo $user->getNickname() ?></span></td>
    <?php foreach (sfConfig::get("app_permission_list", array()) as $permission) { ?>
      <td><?php echo $user->hasPermission($permission) ? yes_icon() : no_icon(); ?></td>
    <?php } ?>
  </tr>
<?php endforeach; ?>
</tbody>
</table>

<?php echo link_to ('Manage users', 'user_admin/list') ?>
</div>