<?php
// auto-generated by sfPropelCrud
// date: 2008/07/24 15:35:45
?>
<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $user->getId() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $user->getEmail() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $user->getName() ?></td>
</tr>
<tr>
<th>Nickname: </th>
<td><?php echo $user->getNickname() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $user->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $user->getUpdatedAt() ?></td>
</tr>
<tr>
<th>Last login: </th>
<td><?php echo $user->getLastLogin() ?></td>
</tr>
<tr>
<th>Account credit: </th>
<td><?php echo $user->getAccountCredit() ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'user_admin/edit?id='.$user->getId()) ?>
&nbsp;<?php echo link_to('list', 'user_admin/list') ?>

<h3>Recent Activity</h3>


