<?php
// auto-generated by sfPropelCrud
// date: 2008/07/24 15:35:45
?>

<?php use_helper("Number"); ?>

<table>
<tbody>
<tr>
<th>Id: </th>
<td><?php echo $user->getId() ?></td>
</tr>
<tr>
<th>Email: </th>
<td><?php echo $user->getEmail() ?></td>
</tr>
<tr>
<th>Name: </th>
<td><?php echo $user->getName() ?></td>
</tr>
<tr>
<th>Nickname: </th>
<td><?php echo $user->getNickname() ?></td>
</tr>
<tr>
<th>Created at: </th>
<td><?php echo $user->getCreatedAt() ?></td>
</tr>
<tr>
<th>Updated at: </th>
<td><?php echo $user->getUpdatedAt() ?></td>
</tr>
<tr>
<th>Last login: </th>
<td><?php echo $user->getLastLogin() ?></td>
</tr>
<tr>
<th>Account credit: </th>
<td><?php echo $user->getAccountCredit() ?></td>
</tr>
<tr>
<th>Permissions: </th>
<td><?php foreach ($user->getUserPermissions() as $p) echo $p->getPermission() . " "; ?></td>
</tr>
</tbody>
</table>
<hr />
<?php echo link_to('edit', 'user_admin/edit?id='.$user->getId()) ?>
&nbsp;<?php echo link_to('list', 'user_admin/list') ?>

<h2>Recent Activity</h2>

<table>
<thead>
<tr>
  <th>ID</th>
  <th>Date</th>
  <th>Activity</th>
  <th>Price</th>
  <th>Quantity</th>
  <th>Credit</th>
  <th>Debit</th>
</tr>
</thead>
<tbody>
<?php foreach ($purchases as $purchase) { ?>
<tr>
	<td><?php echo $purchase->getId(); ?></td>
<?php if ($purchase->getQuantity() < 0) { ?>
	<td><?php echo $purchase->getCreatedAt(); ?></td>
	<td>Purchase: <?php echo link_to($purchase->getProduct()->getTitle(), "product/show?id=".$purchase->getProduct()->getId()); ?></td>
	<td><?php echo format_currency($purchase->getPrice()); ?></td>
	<td><?php echo format_number(-$purchase->getQuantity()); ?></td>
	<td></td>
	<td><?php echo format_currency($purchase->getPrice() * $purchase->getQuantity()); ?></td>
<?php } else { ?>
	<td><?php echo $purchase->getCreatedAt(); ?></td>
	<td>Credit: <?php echo link_to($purchase->getProduct()->getTitle(), "product/show?id=".$purchase->getProduct()->getId()); ?>
		<?php if (!$purchase->getVerifiedBy()) { ?>
		(<?php echo link_to("Unverified", "purchase/list"); ?>)
		<?php } ?>
		</td>
	<td><?php echo format_currency($purchase->getPrice()); ?></td>
	<td><?php echo format_number($purchase->getQuantity()); ?></td>
	<td><?php echo format_currency($purchase->getPrice() * $purchase->getQuantity()); ?></td>
	<td></td>
<?php } ?>
</tr>
<?php } ?>
<tr>
	<th colspan="5">Account Balance</th>
	<th><?php if ($user->getAccountCredit() > 0) echo format_currency($user->getAccountCredit()); ?></th>
	<th><?php if ($user->getAccountCredit() <= 0) echo format_currency($user->getAccountCredit()); ?></th>
</tr>
</tbody>
</table>

